#In this script it is important to set the RepositoryUrl in the *.csproj file

name: NuGet Generation for DoenaSoft

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
env:
  SOURCE_URL: https://api.nuget.org/v3/index.json
  SOLUTION_FILE: CalculateDvdDiscIdLibrary.sln
  PROJECT_FILE: CalculateDvdDiscIdLibrary.csproj
  PROJECT_FOLDER: CalculateDvdDiscIdLibrary
  NUGET_SPEC: DVDProfilerHelper.nuspec
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORMX64: x64
  BUILD_PLATFORMX86: x86
  BUILD_OUTPUTX64: bin\x64\Release
  BUILD_OUTPUTX86: bin\x86\Release
  
jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.7
     
      - name: Restore Nuget
        run: nuget.exe restore ${{ env.SOLUTION_FILE }}
          
      - name: Build x64
        run: msbuild.exe ${{ env.SOLUTION_FILE }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.BUILD_PLATFORMX64 }}

      - name: Build x86
        run: msbuild.exe ${{ env.SOLUTION_FILE }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.BUILD_PLATFORMX86 }}
          
      - name: Pack Nuget
        run: nuget.exe pack ${{ env.PROJECT_FOLDER }}\${{ env.NUGET_SPEC }} -OutputDirectory ${{ env.PROJECT_FOLDER }}

      - name: Push Nuget
        run: nuget.exe push ${{ env.PROJECT_FOLDER }}\*.nupkg -ApiKey ${{secrets.NUGET_API_KEY}} -Source "${{env.SOURCE_URL}}"
